// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Contact Module const
export const FETCH_START = "fetch_start";
export const FETCH_SUCCESS = "fetch_success";
export const FETCH_ERROR = "fetch_error";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";
export const USER_DATA = "user_data";
export const USER_TOKEN_SET = "user_token_set";

//Sticky
export const GET_STICKY = "GET_STICKY";
export const NOTES_UPDATE = "NOTES_UPDATE";
export const FETCH_ALL_NOTES_SUCCESS = "FETCH_ALL_NOTES_SUCCESS";
export const UPDATE_ALL_NOTES_SUCCESS = "UPDATE_ALL_NOTES_SUCCESS";

//Contact
export const GET_All_CONTACT_SUCCESS = "GET_All_CONTACT_SUCCESS";
export const ON_ADD_CONTACT_SUCCESS = "ON_ADD_CONTACT_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

//Account
export const UPDATE_COMPANY_PROFILE = "UPDATE_COMPANY_PROFILE";
export const COMPANY_PROFILE_STEP3 = "COMPANY_PROFILE_STEP3";
export const COMPANY_PROFILE_STEP4 = "COMPANY_PROFILE_STEP4";
export const STEP3_FORM_CHECK_2 = "STEP3_FORM_CHECK_2";
export const STEP3_FORM_CHECK_3 = "STEP3_FORM_CHECK_3";
export const SEND_REQUEST_CHANGE_LICENSE = "SEND_REQUEST_CHANGE_LICENSE";

//User
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

//Profile Company
export const FETCH_PROFILE = "FETCH_PROFILE";
export const SAVE_DATA_INTRO = "SAVE_DATA_INTRO";
export const SAVE_DATA_WEBSITE = "SAVE_DATA_WEBSITE";
export const SAVE_DATA_MEDIA = "SAVE_DATA_MEDIA";
export const SAVE_DATA_SOCIAL = "SAVE_DATA_SOCIAL";
export const SAVE_DATA_ABOUT = "SAVE_DATA_ABOUT";
export const SAVE_DATA_ADDRESS = "SAVE_DATA_ADDRESS";
export const CLEAN_STORE_REDUX = "CLEAN_STORE_REDUX";
export const SAVE_DATA_BACKGROUND = "SAVE_DATA_BACKGROUND";
export const SAVE_LOCAL_BACKGROUND = "SAVE_LOCAL_BACKGROUND";
export const SAVE_DATA_LOGO = "SAVE_DATA_LOGO";
export const SAVE_LOCAL_LOGO = "SAVE_LOCAL_LOGO";

//get user data
export const GET_USER_DATA_START = "GET_USER_DATA_START";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_ERROR = "GET_USER_DATA_ERROR";

//get profile company sdk
// export const FETCH_PROFILE_SDK_START = "FETCH_PROFILE_SDK_START";
// export const FETCH_PROFILE_SDK_SUCCESS = "FETCH_PROFILE_SDK_SUCCESS";
export const CREATE_USER_SDK_SUCCESS = "CREATE_USER_SDK_SUCCESS";
export const CREATE_USER_SDK_START = "CREATE_USER_SDK_START";

export const START_GET_COMMENT_OVERVIEW = "START_GET_COMMENT_OVERVIEW";
export const GET_COMMENT_OVERVIEW_SUCCESS = "GET_COMMENT_OVERVIEW_SUCCESS";
export const GET_COMMENT_OVERVIEW_ERROR = "GET_COMMENT_OVERVIEW_ERROR";
export const START_GET_COMMENT = "START_GET_COMMENT";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";
